BRAND_ALIASES = {
    "gm": "Chevrolet",
    "chevy": "Chevrolet",
    "chevrolet": "Chevrolet",
    "vw": "Volkswagen",
    "volks": "Volkswagen",
    "volkswagen": "Volkswagen",
    "toyota": "Toyota",
    "fiat": "Fiat",
    "ford": "Ford",
    "nissan": "Nissan",
    "renault": "Renault",
    "honda": "Honda",
    "jeep": "Jeep",
    "kia": "Kia",
    "hyundai": "Hyundai",
    "peugeot": "Peugeot",
    "citroen": "Citroën",
    "citroën": "Citroën",
}
